apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "test-vscode-java-maven-overlay-workshop"
spec:
  title: "Java Maven Extensions Test Workshop (OCI Overlay)"
  description: "Workshop to test the Java Maven extensions (OCI Overlay)"
  publish:
    image: "$(image_repository)/test-vscode-java-maven-overlay-workshop-files:$(workshop_version)"
  workshop:
    image: jdk21-environment:*
    files:
    - image:
        url: "$(image_repository)/test-vscode-java-maven-overlay-workshop-files:$(workshop_version)"
      includePaths:
      - /workshop/**
      - /exercises/**
      - /README.md
    packages:
      - name: vscode-java-tools
        files:
          - path: .
            image:
              url: $(image_repository)/vscode-java-tools-oci-overlay:v0.29.2
  session:
    namespaces:
      budget: large
    resources:
      memory: 3Gi
    applications:
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
      console:
        enabled: false
      docker:
        enabled: false
      registry:
        enabled: false
      vcluster:
        enabled: false